# railway.toml for apps/app (encuentra-app service)

[build]
# Nixpacks is usually the default builder, so 'builder' can often be omitted.
# We are in apps/app, so commands are relative to this directory.
installCommand = "bun install --frozen-lockfile"
buildCommand = "bun run build"

[deploy]
# The start command for the Next.js app.
# Railway provides the $PORT environment variable.
startCommand = "bunx next start -p ${PORT}"
